modLoader="javafml"
license="MIT License"
loaderVersion="[35,)"
issueTrackerURL=""
logoFile="logo.png"

[[mods]]
modId="chunker"
displayName="Chunker"
version="${file.jarVersion}"
authors="tofodroid"
description='''
Chunker - Dynamic Chunk Borders
'''

[[dependencies.chunker]]
    modId="forge"
    mandatory=true
    versionRange="[35.0.0,)"
[[dependencies.chunker]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    side="BOTH"